linux: &linux
    os: linux
    language: python
    dist: xenial
    services:
      - docker
osx: &osx 
    os: osx
    language: generic
env:
   global:
     - CONAN_REFERENCE="nptsne/1.0.0rc1"
     - CONAN_USERNAME="lkeb"
     - CONAN_CHANNEL="stable"     
     - CONAN_LOGIN_USERNAME="admin"
     - CONAN_PASSWORD=$CONAN_PASSWORD_SECRET  
     - CONAN_UPLOAD="http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local"
     - CONAN_STABLE_BRANCH_PATTERN="master"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE=1"

ignore:
    - README.md
    - appveyor.yml  

matrix:
   include:
     - <<: *linux
       python: "3.6" 
       env: 
         - CONAN_GCC_VERSIONS=5 
         - CONAN_DOCKER_IMAGE=conanio/gcc5 
         - CONAN_BUILD_TYPES=Release 
         - CONAN_ARCHS=x86_64
        - CONAN_OPTIONS=nptsne:python_version=3.6
     - <<: *linux
       python: "3.7"        
       env:       
         - CONAN_GCC_VERSIONS=5 
         - CONAN_DOCKER_IMAGE=conanio/gcc
         - CONAN_BUILD_TYPES=Release
         - CONAN_ARCHS=x86_64 
         - CONAN_OPTIONS=nptsne:python_version=3.7             
   
     - <<: *osx
       language: generic
       osx_image: xcode10.3
       python: "3.6" 
       env: 
         - CONAN_APPLE_CLANG_VERSIONS=10.0
         - CONAN_BUILD_TYPES=Release
         - CONAN_ARCHS=x86_64
         - CONAN_IS_TRAVIS_OSX=1 
         - OSX_PYTHON=3.6
         - CONAN_OPTIONS=nptsne:python_version=3.6               
          
     - <<: *osx
       language: generic
       osx_image: xcode10.3
       python: "3.7" 
       env: 
         - CONAN_APPLE_CLANG_VERSIONS=10.0
         - CONAN_BUILD_TYPES=Release
         - CONAN_ARCHS=x86_64
         - CONAN_IS_TRAVIS_OSX=1 
         - OSX_PYTHON=3.7
         - CONAN_OPTIONS=nptsne:python_version=3.7                

install:
  - chmod +x .ci/install.sh
  - chmod +x .ci/entry.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
