env:
   global:
     - CONAN_REFERENCE="nptsne/1.0.0rc1"
     - CONAN_USERNAME="lkeb"
     - CONAN_CHANNEL="stable"     
     - CONAN_LOGIN_USERNAME="admin"
     - CONAN_PASSWORD=$CONAN_PASSWORD_SECRET  
     - CONAN_UPLOAD="http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local"
     - CONAN_STABLE_BRANCH_PATTERN="master"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE=1"

ignore:
    - README.md
    - appveyor.yml

language: python        
    
matrix:
   include:
        - os: linux
          python: 3.6 
          dist: xenial
          services:
              - docker
          env:       
              - CONAN_GCC_VERSIONS=5 
              - CONAN_DOCKER_IMAGE=conanio/gcc5
              - CONAN_BUILD_TYPES=Release
              - CONAN_ARCHS=x86_64 
              - python=3.6

        - os: linux
          python: 3.7        
          dist: xenial
          services:
              - docker
          env:       
              - CONAN_GCC_VERSIONS=5 
              - CONAN_DOCKER_IMAGE=conanio/gcc5
              - CONAN_BUILD_TYPES=Release
              - CONAN_ARCHS=x86_64 
              - python=3.7
                
        - os: osx
          language: generic
          osx_image: xcode10.3
          env: 
              - CONAN_APPLE_CLANG_VERSIONS=10.0
              - CONAN_BUILD_TYPES=Release
              - CONAN_ARCHS=x86_64
              - CONAN_IS_TRAVIS_OSX=1 
              - OSX_PYTHON=3.6            
              
        - os: osx
          language: generic        
          osx_image: xcode10.3
          env: 
              - CONAN_APPLE_CLANG_VERSIONS=10.0
              - CONAN_BUILD_TYPES=Release
              - CONAN_ARCHS=x86_64
              - CONAN_IS_TRAVIS_OSX=1 
              - OSX_PYTHON=3.7                          

install:
  - chmod +x .ci/install.sh
  - chmod +x .ci/entry.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
